version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: whatsapp-bot
    ports:
      - "3000:3000"
    volumes:
      - ./.wwebjs_auth:/usr/src/app/.wwebjs_auth
      - ./.baileys_auth:/usr/src/app/.baileys_auth
    restart: unless-stopped
